<head>
    <title><?php print $_SERVER['HTTP_HOST'] ?> /dashboard</title>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />

    <link rel="stylesheet" type="text/css" href="css/ui-lightness/jquery-ui-1.8.21.custom.css" />
    <link rel="stylesheet" type="text/css" href="js/DataTables/media/css/jquery.dataTables.min.css">  
    <link rel="stylesheet" type="text/css" href="css/main.css" />
    <!-- use local JS files. Do not make client fetch from  Google because site might be hosted on a virtual machine with no internet acdess -->
    <script type='text/javascript' src='js/jquery.min.js'></script>
    <script type='text/javascript' src='js/jquery-ui.min.js'></script>
    <script type='text/javascript' src='js/overlib.js'></script>
    <script type='text/javascript' src='js/main.js'></script>
    <script type="text/javascript" charset="utf8" src="js/DataTables/media/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
      var ol_textcolor = "#003366";
      var ol_fgcolor = "#ffffff";
      var ol_bgcolor = "#003366";
      var ol_texsize = "11px";
      var ol_cellpad = "5";
      var ol_height = -1;
      var ol_vpos = ABOVE;
    </script>
</head>

